### PR TITLE
Activerecord 6.0

### PR DESCRIPTION
**Pull request by corneverbruggen**
This adds compatibility for activerecord 6.0. A few notes:

* Activerecord 6.0 requires ruby >= 2.5.0 so did exclude testing for older versions in travis
* Removed ruby 2.2 from Travis. It was raising some errors, and ruby 2.2 has been EOL for a while already. So I thought it was OK to drop support for that.
* It depends on a to-be-released update for rgeo-activerecord with support for activerecord 6.0 for which i already created a pull request rgeo/rgeo-activerecord#48. For now I refererence the activerecord-6.0 branch from which I created that pull request.

I think this pull request addresses both #298 and #292.

### CODE REVIEW

**Comment by barak-neeman** [comment]
Thanks for the rails-6 port, @corneverbruggen . I'm using your fork of the gems until your PRs get merged. I'd also like to report that the rake task to convert a DB into postgis no longer works in rails 6. The rake task to create a new DB works fine. Steps to reproduce:

create a new rails app with --database=postgresql
run rake db:create
add postgis gems into Gemfile
> gem 'activerecord-postgis-adapter', git: 'https://github.com/corneverbruggen/activerecord-postgis-adapter', branch: 'activerecord-6.0'
> gem 'rgeo-activerecord', git: 'https://github.com/corneverbruggen/rgeo-activerecord', branch: 'activerecord-6.0'
run rake db:gis:setup

rake aborted!
NotImplementedError: `ActiveRecord::Base.configurations` in Rails 6 now returns an object instead of a hash. The `values_at` method is not supported.

**Comment by haberbyte** [comment]
The most recent master version of Rails requires another change in SpatialColumn to work.
See https://github.com/haberbyte/activerecord-postgis-adapter/commit/4f6b3adee8dd29cca54bd06179664c48088d1ef5#diff-edb8177bb2adcb1d6115350f9edd5e86

**Comment by aldhsu** [comment]
Along with the changes in https://github.com/haberbyte/activerecord-postgis-adapter/commit/4f6b3adee8dd29cca54bd06179664c48088d1ef5#diff-edb8177bb2adcb1d6115350f9edd5e86. 

The initializer also needs to set an instance variable:
```ruby
#lib/active_record/connection_adapters/postgis/spatial_column.rb
def initializer(name, default, sql_type_metadata = nil, null = true, table_name = nil,
                       default_function = nil, collation = nil, comment = nil, cast_type = nil, opts = nil)
  @sql_type_metadata = sql_type_metadata
   ...
end

**Comment by corneverbruggen** [comment]
Thanks @aldhsu. Setting the instance variable `@sql_type_metadata` is already done by calling `super`, so removed that.

**Comment by corneverbruggen** [comment]
I was wrong about that...
Thanks @haberbyte and @aldhsu.

**Comment by corneverbruggen** [comment]
Not sure what causes this to fail on Travis. The exact same code in [my repository](https://github.com/corneverbruggen/activerecord-postgis-adapter/tree/activerecord-6.0) builds fine in [Travis](https://travis-ci.com/corneverbruggen/activerecord-postgis-adapter/builds/111182931). Seems like there is a difference between build environments of travis-ci.org and travis-ci.com. Anyone experience with this?

**Comment by corneverbruggen** [comment]
Hi @barak-neeman, the rake task for setting up postgis (`db:gis:setup`) should be fixed in the lastest commit (f34ef5c).

**Comment by barak-neeman** [comment]
Tried to rake db:create and it worked fine. Rails 6.0.0.rc1 and my Gemfile looks like this:
gem 'activerecord-postgis-adapter', git: 'https://github.com/corneverbruggen/activerecord-postgis-adapter', branch: 'activerecord-6.0'
gem 'rgeo-activerecord'

Thanks @corneverbruggen !

**Comment by MtnBiker** [comment]
> Tried to rake db:create and it worked fine. Rails 6.0.0.rc1 and my Gemfile looks like this:
> gem 'activerecord-postgis-adapter', git: 'https://github.com/corneverbruggen/activerecord-postgis-adapter', branch: 'activerecord-6.0'
> gem 'rgeo-activerecord'
> 
> Thanks @corneverbruggen !

This worked for me. Before `rails server` failed with mentions of `activerecord-postgis-adapter`. I'm in over my head, but am learning. I wouldn't normally get into prerelease, but I'm updating an app which mainly involved getting to Rails 5.2 and thought I may as well keep going before getting back to refactoring and improving.

The difference is  @barak-neeman is using the current `rgeo-activerecord`? Thank you @corneverbruggen and @barak-neeman and everyone else contributing to this gem.

**Comment by Smcchoi** [comment]
@corneverbruggen travis is fixed in master, did you want to rebase and see if it passes?

**Comment by teeparham** [comment]
Closing in favor of #303. Thanks everyone for the help, and apologies for the delay in getting this out.

**Pull request closed without merging**
