### PR TITLE
Jruby support

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Hi! This is an attempt to get the tests passing for JRuby. The main issue is 3d007649bbfa99d6cff4faeeea05e8aa8567d7af, since JRuby and MRI behave differently here and I don't know what's the expected behavior and whether this should be considered public API at all. 

* JRuby's behavior is actually tested: https://github.com/jruby/activerecord-jdbc-adapter/blob/v1.3.19/test/db/postgresql/simple_test.rb#L173-L180
* I haven't found any tests or documentation for the opposite behavior in `activerecord` but I think it's intentional. I think it happens here: https://github.com/rails/rails/blob/7f18ea14c893cb5c9f04d4fda9661126758332b5/activerecord/lib/active_record/connection_adapters/postgresql/quoting.rb#L59-L68

Opinions?

EDIT: Just linking to the original issue: #198

### CODE REVIEW

**Comment by teeparham** [comment]
Thank you! :tada: :clap:

**Comment by deivid-rodriguez** [comment]
Fuzzy matching does not work... `jruby-9.0` is matched against a prerelease version, while just `jruby` matches it against `jruby-1.7`. We need to be explicit.

**Comment by deivid-rodriguez** [comment]
Thanks! :smile: 

I'd like to ask @kares though about this difference in behavior because whether this `klass.columns` trick is supported or not, I've seen it used in some places, so it'd be good to know what to expect.

**Comment by kares** [comment]
hey! honestly do not know if its much of an issue - recall noticing some `column.default` incompatibilities with MRI on 4.2 but I did not care much (we get type-casted results from elsewhere as well) esp. as the same column code supports older AR versions and no one objected so far. so it is as it is until it is :hear_no_evil:

**Comment by deivid-rodriguez** [comment]
Thanks! Sounds reasonable!

**Comment by teeparham** [comment]
This PR is included in the 3.1.0 gem release: https://rubygems.org/gems/activerecord-postgis-adapter

JRuby folks: please give it a try & report any issues.

**Pull request merged**
