### PR TITLE
Rails 5

### PR DESCRIPTION
**Pull request by afn**
Updates for Rails 5 compatibility (#196)

### CODE REVIEW

**Comment by teeparham** [comment]
There is now a `rails-5` branch. Please rebase on that branch & submit PRs to that branch.

Thanks for this work!

**Comment by pitamonster** [comment]
I'm not sure this is directly a Rails 5 issue, but I am getting the following error which at first I thought was an rgeo thing, but upon closer examination it seems like the adapter maybe is wrongly passing the RGeo object into the wktparser and that is what is causing the parse error. But I'm not sure if that is the root of the problem.

> 2.3.0 :008 > site
 => Site id: nil, user_id: nil, utility_name: "Con Ed", utility_rate: nil, annual_kwh_usage: nil, created_at: nil, updated_at: nil, location_point: nil
> 2.3.0 :009 > site.location_point = params["location_point"]
 => RGeo::Geos::CAPIPointImpl:0x22a24a0 "POINT (-73.96260784645612 40.67387551422036)" 
> 2.3.0 :010 > site
(Object doesn't support #inspect)
 =>  
> 2.3.0 :011 > site.location_point
NoMethodError: undefined method `[]' for #<RGeo::Geos::CAPIPointImpl:0x00000004544940>
        from /usr/local/rvm/gems/ruby-2.3.0/gems/rgeo-0.5.2/lib/rgeo/wkrep/wkb_parser.rb:106:in `parse'
        from /usr/local/rvm/gems/ruby-2.3.0/bundler/gems/activerecord-postgis-adapter-f6cdd732e621/lib/active_record/connection_adapters/postgis/oid/spatial.rb:91:in `cast_value'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/activemodel-5.0.0.beta1/lib/active_model/type/value.rb:36:in `cast'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0.beta1/lib/active_record/attribute.rb:150:in `type_cast'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0.beta1/lib/active_record/attribute.rb:38:in `value'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0.beta1/lib/active_record/attribute_set.rb:42:in `fetch_value'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0.beta1/lib/active_record/attribute_methods/read.rb:78:in `_read_attribute'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0.beta1/lib/active_record/attribute_methods/read.rb:48:in `__temp__c6f636164796f6e6f507f696e647'
        from (irb):11

**Comment by afn** [comment]
There's no way to change the base branch of the pull request, is there? I created a replacement for this PR, #206, which is based against `rails-5`.

**Comment by teeparham** [comment]
@afn No, I don't think you can change the base of the PR once you open it (at least I haven't been able to do that in the past). Thanks for moving your work over to #206. I'm closing this PR.

**Pull request closed without merging**
